# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'num to start'
        required: true
        type: string
      end:
        description: 'num to end'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: repo pulling
      run: |
        git pull origin main --ff-only
    - name: download
      run: |
        python download.py ${{ inputs.start }} ${{ inputs.end }}
    - uses: actions/upload-artifact@v4
      with:
        name: downloaded_files
        path: . # or path/to/artifact
        compression-level: 9 
